name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run:  gcc main.c -o hello

      #artifact
    - name: upload artifacts
      uses: actions/upload-artifact@4.6.0
      with:
       name: package
       path: ${{github.workspace}}/hello
      

  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run:  echo "hello world"
